const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('clockAPI', {
  dragStart: () => ipcRenderer.send('drag-start'),
  dragMove: () => ipcRenderer.send('drag-move'),
  dragEnd: () => ipcRenderer.send('drag-end'),
  resizeStart: (edge) => ipcRenderer.send('resize-start', edge),
  resizeMove: () => ipcRenderer.send('resize-move'),
  resizeEnd: () => ipcRenderer.send('resize-end'),
  todoResizeStart: () => ipcRenderer.send('todo-resize-start'),
  todoResizeMove: (d) => ipcRenderer.send('todo-resize-move', d),
  todoResizeEnd: () => ipcRenderer.send('todo-resize-end'),
  showPanel: (cur) => ipcRenderer.send('show-panel', cur),
  saveSettings: (d) => ipcRenderer.send('save-settings', d),
  loadSettings: () => ipcRenderer.sendSync('load-settings'),
  closeApp: () => ipcRenderer.send('close-app'),
  onSetStyle: (cb) => ipcRenderer.on('set-style', (_, v) => cb(v)),
  onSetTheme: (cb) => ipcRenderer.on('set-theme', (_, v) => cb(v)),
  onSetOpacity: (cb) => ipcRenderer.on('set-opacity', (_, v) => cb(v)),
  onSetBgAlpha: (cb) => ipcRenderer.on('set-bg-alpha', (_, v) => cb(v)),
  onSetClockScale: (cb) => ipcRenderer.on('set-clock-scale', (_, v) => cb(v)),
  onSetAppPadding: (cb) => ipcRenderer.on('set-app-padding', (_, v) => cb(v)),
  onSetTodoTopGap: (cb) => ipcRenderer.on('set-todo-top-gap', (_, v) => cb(v)),
  onSetPctOffset:  (cb) => ipcRenderer.on('set-pct-offset',  (_, v) => cb(v)),
  onSetAppBorderW: (cb) => ipcRenderer.on('set-app-border-w', (_, v) => cb(v)),
  onSetAppBorderR: (cb) => ipcRenderer.on('set-app-border-r', (_, v) => cb(v)),
  onSetAppBorderC: (cb) => ipcRenderer.on('set-app-border-c', (_, v) => cb(v)),
  onSetAppBorderA: (cb) => ipcRenderer.on('set-app-border-a', (_, v) => cb(v)),
  onSetBorderAnim: (cb) => ipcRenderer.on('set-border-anim', (_, v) => cb(v)),
    onSetBorderAnimSpeed: (cb) => ipcRenderer.on('set-border-anim-speed', (_, v) => cb(v)),
    // Shine animation
    onSetShineAnim: (cb) => ipcRenderer.on('set-shine-anim', (_, v) => cb(v)),
    onSetShineSpeed: (cb) => ipcRenderer.on('set-shine-speed', (_, v) => cb(v)),
    onSetShineAngle: (cb) => ipcRenderer.on('set-shine-angle', (_, v) => cb(v)),
    onSetShineWidth: (cb) => ipcRenderer.on('set-shine-width', (_, v) => cb(v)),
    onSetShineOpacity: (cb) => ipcRenderer.on('set-shine-opacity', (_, v) => cb(v)),
    onSetShineColor: (cb) => ipcRenderer.on('set-shine-color', (_, v) => cb(v)),
    onSetShineBorderOpacity: (cb) => ipcRenderer.on('set-shine-border-opacity', (_, v) => cb(v)),
    onSetShineEasing: (cb) => ipcRenderer.on('set-shine-easing', (_, v) => cb(v)),
    onSetShineDelay: (cb) => ipcRenderer.on('set-shine-delay', (_, v) => cb(v)),
    onSetShineDirection: (cb) => ipcRenderer.on('set-shine-direction', (_, v) => cb(v)),
    onSetShineFade: (cb) => ipcRenderer.on('set-shine-fade', (_, v) => cb(v)),
    onSetShineRepeat: (cb) => ipcRenderer.on('set-shine-repeat', (_, v) => cb(v)),
    onSetHands: (cb) => ipcRenderer.on('set-hands', (_, v) => cb(v)),
  onSetSessions: (cb) => ipcRenderer.on('set-sessions', (_, v) => cb(v)),
  onSetBlockOpacity: (cb) => ipcRenderer.on('set-block-opacity', (_, v) => cb(v)),
  onSetBlockAnim: (cb) => ipcRenderer.on('set-block-anim', (_, v) => cb(v)),
  onSetTooltipAnim: (cb) => ipcRenderer.on('set-tooltip-anim', (_, v) => cb(v)),
  onSetTooltipSize: (cb) => ipcRenderer.on('set-tooltip-size', (_, v) => cb(v)),
  onSetOrbitSpeed: (cb) => ipcRenderer.on('set-orbit-speed', (_, v) => cb(v)),
  onSetOrbitStyle: (cb) => ipcRenderer.on('set-orbit-style', (_, v) => cb(v)),
  onSetTodoAnim: (cb) => ipcRenderer.on('set-todo-anim', (_, v) => cb(v)),
  onSetWindowFit: (cb) => ipcRenderer.on('set-window-fit', (_, v) => cb(v)),
  onSetTitleGap: (cb) => ipcRenderer.on('set-title-gap', (_, v) => cb(v)),
  onSetFavorites: (cb) => ipcRenderer.on('set-favorites', (_, v) => cb(v)),
  onSetTodoOpacity: (cb) => ipcRenderer.on('set-todo-opacity', (_, v) => cb(v)),
  onSetTodoBoxOpaque: (cb) => ipcRenderer.on('set-todo-box-opaque', (_, v) => cb(v)),
  onSetTodoBoxOpacity: (cb) => ipcRenderer.on('set-todo-box-opacity', (_, v) => cb(v)),
  onSetCalAnim: (cb) => ipcRenderer.on('set-cal-anim', (_, v) => cb(v)),
  setIgnoreMouse: (b) => ipcRenderer.send('set-ignore-mouse', b),
  fitWindow: (need) => ipcRenderer.send('fit-window', need),
  onWindowResized: (cb) => ipcRenderer.on('window-resized', (_, s) => cb(s)),
  updateTimeInput: (data) => ipcRenderer.send('clock-update-time', data),
  onFocusTime: (cb) => ipcRenderer.on('focus-time', (_, data) => cb(data)),
  onBlurTime: (cb) => ipcRenderer.on('blur-time', () => cb())
});
