const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('clockAPI', {
  dragStart: () => ipcRenderer.send('drag-start'),
  dragMove: () => ipcRenderer.send('drag-move'),
  dragEnd: () => ipcRenderer.send('drag-end'),
  showPanel: (cur) => ipcRenderer.send('show-panel', cur),
  saveSettings: (d) => ipcRenderer.send('save-settings', d),
  loadSettings: () => ipcRenderer.sendSync('load-settings'),
  closeApp: () => ipcRenderer.send('close-app'),
  onSetStyle: (cb) => ipcRenderer.on('set-style', (_, v) => cb(v)),
  onSetTheme: (cb) => ipcRenderer.on('set-theme', (_, v) => cb(v)),
  onSetOpacity: (cb) => ipcRenderer.on('set-opacity', (_, v) => cb(v)),
  onSetHands: (cb) => ipcRenderer.on('set-hands', (_, v) => cb(v)),
  onSetSessions: (cb) => ipcRenderer.on('set-sessions', (_, v) => cb(v)),
  onSetBlockOpacity: (cb) => ipcRenderer.on('set-block-opacity', (_, v) => cb(v)),
  onSetBlockAnim: (cb) => ipcRenderer.on('set-block-anim', (_, v) => cb(v)),
  onSetTooltipAnim: (cb) => ipcRenderer.on('set-tooltip-anim', (_, v) => cb(v)),
  onSetTooltipSize: (cb) => ipcRenderer.on('set-tooltip-size', (_, v) => cb(v)),
  onSetOrbitSpeed: (cb) => ipcRenderer.on('set-orbit-speed', (_, v) => cb(v)),
  onSetOrbitStyle: (cb) => ipcRenderer.on('set-orbit-style', (_, v) => cb(v)),
  onSetTodoAnim: (cb) => ipcRenderer.on('set-todo-anim', (_, v) => cb(v)),
  onSetWindowFit: (cb) => ipcRenderer.on('set-window-fit', (_, v) => cb(v)),
  fitWindow: (need) => ipcRenderer.send('fit-window', need),
  onWindowResized: (cb) => ipcRenderer.on('window-resized', (_, s) => cb(s)),
  updateTimeInput: (data) => ipcRenderer.send('clock-update-time', data),
  onFocusTime: (cb) => ipcRenderer.on('focus-time', (_, data) => cb(data)),
  onBlurTime: (cb) => ipcRenderer.on('blur-time', () => cb())
});
